import turtle


#Set initial variables (This is normally called "Initialize")

turtle.speed(0)
turtle.color('dark blue')
style = ('Arial', 30, 'bold')
x = 0
y = 0
keep_going = True
if keep_going is False:
    print(turtle.pos()[0])
    x = turtle.pos()[0]
    y = turtle.pos()[1]
    turtle.write('u', font = style)
    turtle.penup()
    turtle.setpos(x + 23, y)
    turtle.pendown()
#Initialize screen: move pen to left side
def init():
    turtle.penup()
    turtle.setpos(-470, 400)
    turtle.pendown()
    turtle.width(2)
    x = turtle.pos()[0]
    y = turtle.pos()[1]
#draws the letter "a"
def A():
   turtle.left(60)
   turtle.forward(50)
   turtle.right(120)
   turtle.forward(30)
   turtle.right(120)
   turtle.forward(30)
   turtle.right(120)
   turtle.forward(30)
   turtle.right(120)
   turtle.forward(50)
   turtle.left(60)
   turtle.penup()
   turtle.forward(20)
   turtle.pendown()
   
def B():
    turtle.left(90)
    turtle.forward(45)
    turtle.right(90)
    turtle.forward(10)
    for B in range(36):
        turtle.right(4.7)
        turtle.forward(1)
    turtle.left(170)
    
    for B in range(36):
        turtle.right(5.5)
        turtle.forward(1)
    turtle.forward(1)
    turtle.right(163)
    turtle.penup()
    turtle.forward(20)
    turtle.pendown()
    
def C():
    turtle.penup()
    turtle.forward(20)
    turtle.pendown()
    turtle.left(180)
    for C in range(70):
       turtle.right(2.5)
       turtle.forward(1)
    turtle.right(95)
    turtle.penup()
    turtle.forward(46)
    turtle.left(90)
    turtle.forward(20)
    turtle.pendown()
def D():   
    #turtle.penup()
    #turtle.forward(20)
    #turtle.pendown()
    for C in range(70):
       turtle.left(2.5)
       turtle.forward(1)
    turtle.left(95)    
    turtle.forward(47)
    turtle.left(90)
    turtle.penup()
    turtle.forward(26)
    #x = x + 20
    #turtle.setpos(x, y)
    turtle.pendown()
def E():
    turtle.left(90)
    turtle.forward(45)
    turtle.right(90)
    turtle.forward(30)
    turtle.left(180)
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(25)
    turtle.left(180)
    turtle.forward(25)
    turtle.left(90)
    turtle.forward(25)
    turtle.left(90)
    turtle.forward(30)
    turtle.penup()
    turtle.forward(5)
    turtle.pendown()
def F():
    turtle.left(90)
    turtle.forward(45)
    turtle.right(90)
    turtle.forward(30)
    turtle.left(180)
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(25)
    turtle.left(180)
    turtle.forward(25)
    turtle.left(90)
    turtle.forward(25)
    turtle.left(90)
    turtle.penup()
    turtle.forward(35)
    turtle.pendown()
def G():
   turtle.penup()
   turtle.forward(20)
   turtle.pendown()
   turtle.left(180)
   for C in range(70):
      turtle.right(2.5)
      turtle.forward(1)
   turtle.right(95)
   turtle.penup()
   turtle.forward(47)
   turtle.pendown()
   turtle.left(180)
   turtle.forward(20)
   turtle.left(90)
   turtle.forward(15)
   turtle.left(180)
   turtle.forward(15)
   turtle.right(90)
   turtle.forward(20)
   turtle.left(90)
   turtle.penup()
   turtle.forward(20)
   turtle.pendown()
def H():
    turtle.left(90)
    turtle.forward(45)
    turtle.left(180)
    turtle.forward(22.5)
    turtle.left(90)
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(22.5)
    turtle.left(180)
    turtle.forward(45)
    turtle.left(90)
    turtle.penup()
    turtle.forward(20)
    turtle.pendown()
def I():
    turtle.forward(25)
    turtle.left(180)
    turtle.forward(12.5)
    turtle.right(90)
    turtle.forward(45)
    turtle.right(90)
    turtle.forward(12.5)
    turtle.left(180)
    turtle.forward(25)
    turtle.left(180)
    turtle.forward(25)
    turtle.penup()
    turtle.right(90)
    turtle.forward(45)
    turtle.left(90)
    turtle.forward(20)
    turtle.pendown()
def J():
    turtle.penup()
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(15)
    turtle.pendown()
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(20)
    turtle.left(180)
    turtle.forward(40)
    turtle.left(180)
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(30)
    turtle.right(45)
    turtle.forward(10)
    turtle.right(45)
    turtle.forward(10)
    turtle.right(45)
    turtle.forward(5)
    turtle.right(45)
    turtle.forward(5)
    turtle.left(180)
    turtle.forward(5)
    turtle.left(45)
    turtle.forward(5)
    turtle.left(45)
    turtle.forward(10)
    turtle.penup()
    turtle.right(90)
    turtle.forward(8)
    turtle.left(90)
    turtle.forward(35)
    turtle.pendown()                    
def K():
    turtle.left(90)
    turtle.forward(45)
    turtle.left(180)
    turtle.forward(22.5)
    turtle.left(135)
    turtle.forward(25)
    turtle.left(180)
    turtle.forward(25)
    turtle.left(180)
    turtle.right(91)
    turtle.forward(25)
    turtle.left(180)
    turtle.forward(25)
    turtle.left(91)
    turtle.left(45)
    turtle.forward(22.5)
    turtle.penup()
    turtle.left(90)
    turtle.forward(27)
    turtle.pendown()
def L():
    turtle.left(90)
    turtle.forward(45)
    turtle.left(180)
    turtle.forward(45)
    turtle.left(90)
    turtle.forward(20)
    turtle.penup()
    turtle.forward(20)
    turtle.pendown()
def M():
    turtle.left(90)
    turtle.forward(45)
    turtle.right(135)
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(30)
    turtle.right(135)
    turtle.forward(45)
    turtle.penup()
    turtle.left(90)
    turtle.forward(20)
    turtle.pendown()
    
def N():
    turtle.left(90)
    turtle.forward(45)
    turtle.right(135)
    turtle.forward(49.244289009)
    turtle.left(135)
    turtle.forward(35)
    turtle.right(180)
    turtle.forward(45)
    turtle.left(90)
    turtle.penup()
    turtle.forward(20)
    turtle.pendown()
def O():
    turtle.penup()
    turtle.forward(25)
    turtle.pendown()
    for C in range(70):
       turtle.left(5)
       turtle.forward(2)
    turtle.left(12.3)
    turtle.forward(4)
    turtle.right(2.5)
    turtle.penup()
    turtle.forward(40)
    turtle.pendown()
def P():
    turtle.left(90)
    turtle.forward(45)
    turtle.right(90)
    for C in range(35):
     turtle.right(5)
     turtle.forward(1)
    turtle.left(85)
    turtle.forward(22)
    turtle.left(90)
    turtle.penup()
    turtle.forward(20)
    turtle.pendown()
def Q():
    turtle.penup()
    turtle.forward(25)
    turtle.pendown()
    for C in range(70):
      turtle.left(5)
      turtle.forward(2)
    turtle.left(12.3)
    turtle.forward(4)
    turtle.right(2.5)
    turtle.forward(20)
    turtle.penup()
    turtle.forward(20)
    turtle.pendown()
def R():
    turtle.left(90)
    turtle.forward(45)
    turtle.right(90)
    for C in range(35):
     turtle.right(5)
     turtle.forward(1)
    turtle.left(85)
    turtle.left(45)
    turtle.forward(30)
    turtle.left(45)
    turtle.penup()
    turtle.forward(20)
    turtle.pendown()
def S():
    turtle.pendown()
    turtle.forward(10)
    for C in range(36):
     turtle.left(5)
     turtle.forward(1)
    for C in range(36):
     turtle.right(5)
     turtle.forward(1)
    turtle.forward(10)
    turtle.penup()
    turtle.right(90)
    turtle.forward(45)
    turtle.left(90)
    turtle.forward(20)
    turtle.pendown()
#   turtle.left(22.5)
#   turtle.forward(15)
#   turtle.left(22.5)
#   turtle.forward(15)
#   turtle.left(45)
#   turtle.forward(10)
#   turtle.left(90)
#   turtle.right(27.5)
#   turtle.forward(15)
#   turtle.right(40)
#   turtle.forward(15)
#   turtle.right(90)
#   turtle.forward(20)
def T():
    turtle.penup()
    turtle.forward(10)
    turtle.pendown()
    turtle.left(90)
    turtle.forward(45)
    turtle.left(90)
    turtle.forward(25)
    turtle.left(180)
    turtle.forward(50)
    turtle.right(90)
    turtle.penup()
    turtle.forward(45)
    turtle.left(90)
    turtle.forward(20)
    turtle.pendown()
def U():
    turtle.left(90)
    turtle.forward(45)
    turtle.right(90)
    turtle.penup()
    turtle.forward(22)
    turtle.right(90)
    turtle.pendown()
    turtle.forward(35)
    for C in range(35):
     turtle.right(5)
     turtle.forward(1)
    turtle.left(180)
    turtle.forward(11)
    turtle.left(85)
    turtle.penup()
    turtle.forward(40)
    turtle.pendown()
    
def V():
   turtle.left(100)
   turtle.forward(45)
   turtle.left(180)
   turtle.forward(45)
   turtle.right(100)
   turtle.left(180)
   turtle.left(75)
   turtle.forward(45)
   turtle.right(165)
   turtle.penup()
   turtle.forward(43)
   turtle.left(90)
   turtle.forward(20)
   turtle.pendown()
def W():
    turtle.left(90)
    turtle.forward(45)
    turtle.left(180)
    turtle.forward(45)
    turtle.left(135)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(30)
    turtle.left(135)
    turtle.forward(45)
    turtle.left(180)
    turtle.forward(45)
    turtle.penup()
    turtle.left(90)
    turtle.forward(20)
    turtle.pendown()
def X():
    turtle.left(45)
    turtle.forward(45)
    turtle.left(180)
    turtle.forward(22.5)
    turtle.right(90)
    turtle.forward(22.5)
    turtle.left(180)
    turtle.forward(45)
    turtle.left(45)
    turtle.penup()
    turtle.forward(20)
    turtle.pendown()
def Y():
    turtle.left(90)
    turtle.forward(22.5)
    turtle.left(45)
    turtle.forward(20)
    turtle.left(180)
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(20)
    turtle.right(135)
    turtle.penup()
    turtle.forward(37)
    turtle.left(90)
    turtle.forward(20)
    turtle.pendown()
    
def Z():
    turtle.left(45)
    turtle.forward(45)
    turtle.left(135)
    turtle.forward(36)
    turtle.left(90)
    turtle.penup()
    turtle.forward(31.8)
    turtle.left(90)
    turtle.pendown()
    turtle.forward(45)
    turtle.penup()
    turtle.forward(20)
    turtle.pendown()
def number_1():
    turtle.left(90)
    turtle.forward(45)
    turtle.left(135)
    turtle.forward(15)
    turtle.left(45)
    turtle.penup()
    turtle.forward(35)
    turtle.left(90)
    turtle.forward(20)
    turtle.pendown()
def number_2():
    turtle.left(45)
    turtle.forward(45)
    turtle.left(45)
    for C in range(36):
     turtle.left(5)
     turtle.forward(1)
    turtle.penup() 
    turtle.forward(31)
    turtle.left(90)
    turtle.pendown()
    turtle.forward(30)
    turtle.penup()
    turtle.forward(15)
    turtle.pendown()
def number_3():
    turtle.pendown()
    turtle.forward(10)
    for C in range(36):
     turtle.left(5)
     turtle.forward(1)
    turtle.left(180) 
    for C in range(36):
     turtle.left(5)
     turtle.forward(1)
    turtle.forward(10)
    turtle.left(180)
    turtle.penup()
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(45)
    turtle.left(90)
    turtle.forward(20)
    turtle.pendown()
def number_4():
    turtle.penup()
    turtle.forward(20)
    turtle.pendown()
    turtle.left(90)
    turtle.forward(40)
    turtle.left(180)
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(20)
    turtle.penup()
    turtle.left(180)
    turtle.forward(40)
    turtle.left(90)
    turtle.forward(40)
    turtle.pendown()
def number_5():
    turtle.left(22.5)
    turtle.forward(15)
    turtle.left(22.5)
    turtle.forward(15)
    turtle.left(45)
    turtle.forward(10)
    turtle.left(90)
    turtle.right(27.5)
    turtle.forward(15)
    turtle.right(56)
    turtle.forward(15)
    turtle.right(90)
    turtle.forward(20)
    turtle.penup()
    turtle.right(96.75)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(20)
    turtle.pendown()
def number_6():
    turtle.penup()
    turtle.forward(25)
    turtle.pendown()
    for C in range(60):
       turtle.left(10)
       turtle.forward(2)
    turtle.left(180)
    turtle.forward(30)
    turtle.right(60)
    turtle.penup()
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(43)
    turtle.left(90)
    turtle.pendown()
def number_7():
    turtle.left(45)
    turtle.forward(45)
    turtle.left(135)
    turtle.forward(30)
    turtle.left(90)
    turtle.penup()
    turtle.forward(31.6)
    turtle.left(90)
    turtle.forward(35)
    turtle.pendown()
def number_8():
    turtle.penup()
    turtle.forward(25)
    turtle.pendown()
    for C in range(54):
       turtle.left(10)
       turtle.forward(2)
    turtle.left(180)
    for C in range(54):
       turtle.left(10)
       turtle.forward(2)
    turtle.left(180)
    turtle.penup()
    turtle.right(90)
    turtle.forward(45)
    turtle.left(90)
    turtle.forward(25)
    turtle.pendown()
def number_9():
    turtle.left(90)
    turtle.forward(45)
    turtle.left(90)
    for C in range(35):
     turtle.left(5)
     turtle.forward(1)
    turtle.left(90.3)
    turtle.forward(22)
    turtle.penup()
    turtle.right(85.5)
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(45)
    turtle.left(90)
    turtle.pendown()
def number_0():
    turtle.penup()
    turtle.forward(25)
    turtle.pendown()
    for C in range(135):
       turtle.left(5)
       turtle.forward(2)
    turtle.left(90)
    turtle.forward(45)
    turtle.left(45)
    turtle.left(180)
    turtle.penup()
    turtle.forward(38)
    turtle.left(90)
    turtle.forward(20)
    turtle.pendown()
def exclamation():
    turtle.left(90)
    turtle.forward(10)
    turtle.penup()
    turtle.forward(10)
    turtle.pendown()
    turtle.forward(25)
    turtle.penup()
    turtle.left(180)
    turtle.forward(45)
    turtle.left(90)
    turtle.forward(20)
    turtle.pendown()
def peiriod():
    turtle.left(90)
    turtle.forward(10)
    turtle.left(180)
    turtle.forward(10)
    turtle.penup()
    turtle.left(90)
    turtle.forward(20)
    turtle.pendown()
#puts in a space between letters
def space():
     x = turtle.pos()[0]
     y = turtle.pos()[1]
     turtle.penup()
     turtle.setpos(x + 50, y)
     turtle.pendown()
def question():
    turtle.left(90)
    turtle.penup()
    turtle.forward(30)
    turtle.pendown()
    for C in range(36):
     turtle.right(5)
     turtle.forward(1)
    turtle.forward(15)
    turtle.penup()
    turtle.forward(5)
    turtle.pendown()
    turtle.forward(9)
    turtle.left(90)
    turtle.penup()
    turtle.forward(20)
    turtle.pendown()
def next_line():
    x = -470
    y = turtle.pos()[1]
    turtle.penup()
    turtle.setpos(x, y - 50)
    turtle.pendown()

#-------------------------------------------------------------------------------------
init()
turtle.onkeypress(space, "space")
turtle.onkeypress(A, "a")
turtle.onkeypress(B, "b")
turtle.onkeypress(C, "c")
turtle.onkeypress(D, "d")
turtle.onkeypress(E, "e")
turtle.onkeypress(F, "f")
turtle.onkeypress(G, "g")
turtle.onkeypress(H, "h")
turtle.onkeypress(I, "i")
turtle.onkeypress(J, "j")
turtle.onkeypress(K, "k")
turtle.onkeypress(L, "l")
turtle.onkeypress(M, "m")
turtle.onkeypress(N, "n")
turtle.onkeypress(O, "o")
turtle.onkeypress(P, "p")
turtle.onkeypress(Q, "q")
turtle.onkeypress(R, "r")
turtle.onkeypress(S, "s")
turtle.onkeypress(T, "t")
turtle.onkeypress(U, "u")
turtle.onkeypress(V, "v")
turtle.onkeypress(W, "w")
turtle.onkeypress(X, "x")
turtle.onkeypress(Y, "y")
turtle.onkeypress(Z, "z")
turtle.onkeypress(number_1, "1")
turtle.onkeypress(number_2, "2")
turtle.onkeypress(number_3, "3")
turtle.onkeypress(number_4, "4")
turtle.onkeypress(number_5, "5")
turtle.onkeypress(number_6, "6")
turtle.onkeypress(number_7, "7")
turtle.onkeypress(number_8, "8")
turtle.onkeypress(number_9, "9")
turtle.onkeypress(number_0, "0")
turtle.onkeypress(exclamation, "!")
turtle.onkeypress(peiriod, ".")
turtle.onkeypress(question, "?")
turtle.onkeypress(next_line, "Return")
turtle.listen()






